modLoader="javafml" #mandatory
loaderVersion="[28,]" #mandatory
credits="" #optional
authors="Gigabit101, Cloudhunter, Creeperhost" #optional
[[mods]] #mandatory
    modId="minetogether" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="MineTogether" #mandatory
    description='''
'''
[[dependencies.minetogether]]
    modId="minecraft"
    mandatory=false
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"